// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: worker.proto

package proto_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignMapTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileInfo      []*MapFileInfo         `protobuf:"bytes,1,rep,name=file_info,json=fileInfo,proto3" json:"file_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignMapTaskReq) Reset() {
	*x = AssignMapTaskReq{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignMapTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignMapTaskReq) ProtoMessage() {}

func (x *AssignMapTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignMapTaskReq.ProtoReflect.Descriptor instead.
func (*AssignMapTaskReq) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *AssignMapTaskReq) GetFileInfo() []*MapFileInfo {
	if x != nil {
		return x.FileInfo
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type MapFileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	From          int64                  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To            int64                  `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapFileInfo) Reset() {
	*x = MapFileInfo{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapFileInfo) ProtoMessage() {}

func (x *MapFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapFileInfo.ProtoReflect.Descriptor instead.
func (*MapFileInfo) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *MapFileInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *MapFileInfo) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *MapFileInfo) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

type AssignReduceTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignReduceTaskReq) Reset() {
	*x = AssignReduceTaskReq{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignReduceTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignReduceTaskReq) ProtoMessage() {}

func (x *AssignReduceTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignReduceTaskReq.ProtoReflect.Descriptor instead.
func (*AssignReduceTaskReq) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{4}
}

type HealthRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRes) Reset() {
	*x = HealthRes{}
	mi := &file_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRes) ProtoMessage() {}

func (x *HealthRes) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRes.ProtoReflect.Descriptor instead.
func (*HealthRes) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{5}
}

func (x *HealthRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\"=\n" +
	"\x10AssignMapTaskReq\x12)\n" +
	"\tfile_info\x18\x01 \x03(\v2\f.MapFileInfoR\bfileInfo\"\x1c\n" +
	"\x06Result\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"N\n" +
	"\vMapFileInfo\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\x03R\x02to\"\x15\n" +
	"\x13AssignReduceTaskReq\"\a\n" +
	"\x05Empty\"#\n" +
	"\tHealthRes\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status2\x9d\x01\n" +
	"\x06Worker\x12+\n" +
	"\rAssignMapTask\x12\x11.AssignMapTaskReq\x1a\a.Result\x121\n" +
	"\x10AssignReduceTask\x12\x14.AssignReduceTaskReq\x1a\a.Result\x12\x15\n" +
	"\x03End\x12\x06.Empty\x1a\x06.Empty\x12\x1c\n" +
	"\x06Health\x12\x06.Empty\x1a\n" +
	".HealthResB\rZ\v./proto_genb\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_worker_proto_goTypes = []any{
	(*AssignMapTaskReq)(nil),    // 0: AssignMapTaskReq
	(*Result)(nil),              // 1: Result
	(*MapFileInfo)(nil),         // 2: MapFileInfo
	(*AssignReduceTaskReq)(nil), // 3: AssignReduceTaskReq
	(*Empty)(nil),               // 4: Empty
	(*HealthRes)(nil),           // 5: HealthRes
}
var file_worker_proto_depIdxs = []int32{
	2, // 0: AssignMapTaskReq.file_info:type_name -> MapFileInfo
	0, // 1: Worker.AssignMapTask:input_type -> AssignMapTaskReq
	3, // 2: Worker.AssignReduceTask:input_type -> AssignReduceTaskReq
	4, // 3: Worker.End:input_type -> Empty
	4, // 4: Worker.Health:input_type -> Empty
	1, // 5: Worker.AssignMapTask:output_type -> Result
	1, // 6: Worker.AssignReduceTask:output_type -> Result
	4, // 7: Worker.End:output_type -> Empty
	5, // 8: Worker.Health:output_type -> HealthRes
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
